EPM.Web/Controllers/MaintenanceController.cs
namespace DBSoft.EPMWeb.Controllers
{
    using System.Threading.Tasks;
    using Annotations;
    using EPM.DAL.Services.AccountApi;
    using AutoMapper;
    using EPM.DAL.DTOs;
    using EPM.DAL.Interfaces;
	using EPM.DAL.Requests;
    using EPM.Logic;
    using Models.Account;
	using Models.Maintenance;
	using Support.Filters;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Web.Mvc;

	[RequireDatabaseAuthentication]
	public class MaintenanceController : EpmController
	{
		private readonly IConfigurationService _config;
	    private readonly IConfigurationProcessor _configProcessor;
		private readonly IUniverseService _universeService;
	    private readonly IAccountService _accounts;
	    private readonly IEveAccountProcessor _accountProcessor;

	    [UsedImplicitly]
	    public MaintenanceController(IConfigurationProcessor configurationProcessor, 
            IUniverseService universeService, IAccountService accounts, IEveAccountProcessor accountProcessor,
            IConfigurationService config)
		{
            _config = config;
	        _configProcessor = configurationProcessor;
            _universeService = universeService;
		    _accounts = accounts;
	        _accountProcessor = accountProcessor;

	        Mapper.CreateMap<ConfigurationModel, ConfigurationSettingsDTO>()
				.ForMember(m => m.FactoryLocation, opt => opt.MapFrom(m => m.FactoryID))
				.ForMember(m => m.MarketSellLocation, opt => opt.MapFrom(m => m.MarketSellID))
                .ForMember(m => m.MarketBuyLocation, opt => opt.MapFrom(m => m.MarketBuyID))
                .ForMember(m => m.PosLocation, opt => opt.MapFrom(m => m.PosLocationID));
			Mapper.CreateMap<ConfigurationSettingsDTO, ConfigurationModel>()
				.ForMember(m => m.FactoryID, opt => opt.MapFrom(m => m.FactoryLocation))
				.ForMember(m => m.MarketSellID, opt => opt.MapFrom(m => m.MarketSellLocation))
                .ForMember(m => m.MarketBuyID, opt => opt.MapFrom(m => m.MarketBuyLocation))
                .ForMember(m => m.PosLocationID, opt => opt.MapFrom(m => m.PosLocation));
			Mapper.CreateMap<AccountDTO, AccountModel>().ReverseMap();
		}

		public ActionResult Index()
		{
			return View();
		}

		public ActionResult Configuration()
		{
			var settings = _config.List(Token);
			var model = Mapper.Map<ConfigurationModel>(settings);
			model.ConfigurationValid = _configProcessor.ConfigurationIsValid(Token);

			return View(model);
		}

		[HttpPost]
		public JsonResult Configuration(ConfigurationModel config)
		{
			var settings = Mapper.Map<ConfigurationSettingsDTO>(config);
			_config.SaveSettings(Token, settings);
			return JsonResponse(null);
		}

		public ActionResult Accounts()
		{
			var model = new AccountsModel
				{
					Accounts = Mapper.Map<IEnumerable<AccountDTO>, List<AccountModel>>(
						_accounts.List(new AccountRequest {Token = Token, IncludeDeleted = true}))
				};
			return View(model);
		}

		[HttpPost]
		public async Task<JsonResult> SaveAccount(AccountModel model)
		{
			try
			{
				var account = Mapper.Map<AccountDTO>(model);
				var result = await _accountProcessor.SaveAccount(account, Token);
				return Json(new
				{
					Success = true,
					Model = result
				});
			}
			catch (Exception e)
			{
				var result = Json(new { Success = false, e.Message });
				return result;
			}
		}

		private JsonResult JsonResponse(dynamic model)
		{
			return Json(new
				{
					Success = true,
					Model = model
				}, JsonRequestBehavior.AllowGet);
		}

		public async Task<JsonResult> RegionLookup(int regionId)
		{
			return JsonResponse((await _universeService
							.ListRegions())
							.SingleOrDefault(f => f.RegionID == regionId));
		}

		public JsonResult StationLookup(int stationId)
		{
            var result = _universeService
                        .ListStations()
                        .SingleOrDefault(f => f.StationID == stationId);
			return JsonResponse(result);
		}

        public JsonResult StationList(string stationPartial)
		{
			return JsonResponse(_universeService
						.ListStations()
						.Where(f => f.StationName.StartsWith(stationPartial, StringComparison.InvariantCultureIgnoreCase))
						.OrderBy(f => f.StationName));
		}

        public JsonResult SolarSystemList(string systemPartial)
	    {
            return JsonResponse(_universeService.ListSolarSystems()
                .Where(f => f.SolarSystemName.StartsWith(systemPartial, StringComparison.InvariantCultureIgnoreCase))
                .OrderBy(f => f.SolarSystemName));
	    }

        public JsonResult SolarSystemLookup(int? solarSystemId)
        {
            return JsonResponse(_universeService
                .ListSolarSystems()
                .SingleOrDefault((f => f.SolarSystemID == solarSystemId)));
        }
	}
}

EPM.Web/Controllers/ProductionController.cs
namespace DBSoft.EPMWeb.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;
    using Annotations;
    using System;
    using AutoMapper;
    using EPM.DAL.DTOs;
    using EPM.DAL.Interfaces;
    using EPM.DAL.Requests;
    using EPM.DAL.Services.Contracts;
    using EPM.Logic;
    using System.Web.Mvc;
    using Models.Production;
    using Models.Reporting;
    using Support.Filters;

    [RequireDatabaseAuthentication]
    public class ProductionController : EpmController
    {
        private readonly IMarketRestockService _marketRestockService;
        private readonly IProductionQueueService _productionQueueService;
        private readonly IProductionMaterialService _productionMaterialService;
        private readonly IItemService _itemService;
        private readonly IConfigurationService _config;
        private readonly IMarketRepriceService _marketRepriceService;
        private readonly IMaterialPurchaseService _materialPurchaseService;
        private readonly IMaterialItemService _materialItemService;
        private readonly IImportManager _importer;
        private readonly IContractService _contractService;

        [UsedImplicitly]
        public ProductionController(IMarketRestockService marketRestockService, IProductionQueueService productionQueueService,
            IProductionMaterialService productionMaterialService, IItemService itemService,
            IConfigurationService config, IMarketRepriceService marketRepriceService,
            IMaterialPurchaseService materialPurchaseService, IMaterialItemService materialItemService, IEpmConfig settings,
            IContractService contractService, IImportManager importer)
        {
            _marketRestockService = marketRestockService;
            _productionQueueService = productionQueueService;
            _productionMaterialService = productionMaterialService;
            _itemService = itemService;
            _config = config;
            _marketRepriceService = marketRepriceService;
            _materialPurchaseService = materialPurchaseService;
            _materialItemService = materialItemService;
            _importer = importer;
            _contractService = contractService;
            Mapper.CreateMap<MaterialItemDTO, MaterialItemModel>();

        }
        public ActionResult Index()
        {
            return View();
        }

        [RequireCompleteConfiguration]
        public ActionResult RefreshApi()
        {
            var model = new RefreshApiModel();
            return View(model);
        }

        [HttpPost]
        public JsonResult StartApiRefresh()
        {
            Task.Run(() => _importer.StartImport(Token));
            return Json("OK");
        }

        public JsonNetResult GetApiStatus()
        {
            var items = _importer.List(Token).OrderBy(f => f.ApiName).ToList();
            return new JsonNetResult
            {
                Data = new { status = "OK", data = items },
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        public ActionResult MarketRestock()
        {
            return View(new PostSellOrdersModel(_marketRestockService, Token));
        }

        public ActionResult MarketReprice()
        {
            var model = new UpdateSellOrderModel(_marketRepriceService, Token);
            return View(model);
        }

        public ActionResult ItemBuild()
        {
            return View(new ProductionQueueModel(_productionQueueService, Token));
        }

        public ActionResult ItemMaintenance()
        {
            return View();
        }

        public ActionResult BuildableItemList()
        {
            var model = new BuildableItemListModel(_itemService, Token, System.Web.HttpContext.Current.Request.Url.PathAndQuery);
            return PartialView(model);
        }

        public ActionResult MaterialItem(int itemID, string returnUrl)
        {
            var item = _materialItemService
                .List(Token)
                .Single(f => f.ItemID == itemID);
            var model = Mapper.Map<MaterialItemModel>(item);
            model.ReturnUrl = returnUrl;
            return View("MaterialItem", model);
        }

        [HttpPost]
        public ActionResult MaterialItem(MaterialItemModel item)
        {
            _itemService.UpdateMaterial(new UpdateMaterialRequest
            {
                Token = Token,
                ItemID = item.ItemID,
                BounceFactor = item.BounceFactor
            });
            return Redirect(item.ReturnUrl);
        }

        [HttpPost]
        public JsonResult SaveItem(BuildableItemModel model)
        {
            try
            {
                _itemService.UpdateItem(new UpdateItemRequest
                {
                    ItemID = model.ItemID,
                    Token = Token,
                    MinimumStock = model.MinimumStock,
                    PerJobAdditionalCost = model.PerJobAdditionalCost
                });
                return Json(new
                {
                    Success = true
                });
            }
            catch (Exception e)
            {
                var result = Json(new { Success = false, e.Message });
                return result;
            }

        }

        [HttpPost]
        public JsonResult SaveMaterial(MaterialItemModel model)
        {
            try
            {
                _itemService.UpdateMaterial(new UpdateMaterialRequest
                {
                    ItemID = model.ItemID,
                    Token = Token,
                    BounceFactor = model.BounceFactor
                });
                return Json(new
                {
                    Success = true,
                    LastModified = DateTime.UtcNow.ToString("d")
                });
            }
            catch (Exception e)
            {
                var result = Json(new { Success = false, e.Message });
                return result;
            }

        }

        public ActionResult MaterialItemList()
        {
            var model = new MaterialItemListModel(_materialItemService, Token, System.Web.HttpContext.Current.Request.Url.PathAndQuery);
            return PartialView(model);
        }

        public ActionResult PurchaseRelist()
        {
            var model = new PostBuyOrderModel(_materialPurchaseService, Token, IsEveClient);
            return View(model);
        }

        public ActionResult PurchaseReprice()
        {
            var model = new UpdateBuyOrderModel(_materialPurchaseService, Token);
            return View(model);
        }

        public ActionResult InboundContract()
        {
            var model = new InboundContractModel(_contractService, Token);
            return View(model);
        }

        public ActionResult OutboundContract()
        {
            var model = new OutboundContractModel(_contractService, _config, Token);
            return View(model);
        }

        public ActionResult ProductionMaterial()
        {
            return View(new ProductionMaterialModel(_productionMaterialService, Token,
                System.Web.HttpContext.Current.Request.Url.PathAndQuery));

        }
    }
}

EPM.Web/Controllers/ReportingController.cs
namespace DBSoft.EPMWeb.Controllers
{
    using System.Diagnostics;
    using System.Threading.Tasks;
    using Annotations;
    using System;
	using System.Web.Mvc;
    using EPM.DAL.Services;
    using EPM.DAL.Services.ItemCosts;
    using EPM.DAL.Services.Transactions;
    using Models.Reporting;
    using Support.Filters;

	[RequireDatabaseAuthentication]
	public partial class ReportingController : EpmController
	{
		private readonly IItemTransactionService _sales;
		private readonly IItemCostService _itemCostService;
	    private readonly IMaterialVarianceService _variances;
	    private readonly IReportModelBuilder _reportModelBuilder;

        [UsedImplicitly]
        public ReportingController(IItemTransactionService sales, IItemCostService itemCostService, IMaterialVarianceService variances, 
            IReportModelBuilder reportModelBuilder)
        {
            _sales = sales;
            _itemCostService = itemCostService;
            _variances = variances;
            _reportModelBuilder = reportModelBuilder;
        }

		public virtual ActionResult Index()
		{
			return View();
		}

		public virtual ActionResult ItemCostTrend()
		{
			return View(new ItemCostTrendModel(_itemCostService, Token));
		}

		public virtual ActionResult MaterialCostTrend()
		{
			return View(new MaterialCostTrendModel(_variances, Token));
		}

		public virtual ActionResult ItemCostTrendDetail(string itemName)
		{
			return View(new ItemCostTrendDetailModel(_variances, itemName, Token));
		}

		public virtual ActionResult ItemSalesRange(DateTime fromDate, DateTime toDate)
		{
		    Debug.Assert(Request.Url != null, "Request.Url != null");
		    var model = new ItemSaleModel(_sales, fromDate, toDate, Token, string.Format("{0}://{1}/{2}", 
                Request.Url.Scheme, Request.Url.Host, Request.Url.AbsolutePath));
			return View("ItemSales", model);
		}

		public virtual ActionResult ItemSales(DateTime? fromDate, DateTime? toDate)
		{
			fromDate = fromDate ?? DateTime.UtcNow.AddDays(-7);
			toDate = toDate ?? DateTime.UtcNow.AddDays(-1);
			return ItemSalesRange(fromDate.Value, toDate.Value);
		}

		public virtual ActionResult ItemTransaction(string itemID, DateTime fromDate, DateTime toDate)
		{
			var model = new ItemTransactionModel(_sales, int.Parse(itemID), fromDate, toDate, Token);
			return View(model);
		}

		public virtual ActionResult DailySales()
		{
			var model = new DailySaleModel(_sales, Token);
			return View(model);
		}

		public virtual ActionResult MonthlySales()
		{
			var model = new MonthlySaleModel(_sales, Token);
			return View(model);
		}

        public async Task<ActionResult> MarketResearch()
        {
            var model = await Task.Run(() => _reportModelBuilder.CreateMarketResearchModel(Token));
            return View(model);
        }

        public ActionResult TransactionAudit()
        {
            var model = _reportModelBuilder.CreateTransactionAuditModel(Token);
            return View(model);
        }

        public ActionResult SubscriberSales(DateTime? fromDate, DateTime? toDate)
        {
            var model = _reportModelBuilder.CreateSubscriberSalesModel(Token, fromDate, toDate);
            return View(model);
        }
	}
}

EPM.Web/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
@using DBSoft.EPM.DAL.Services

<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width" />

    @Scripts.Render("~/bundles/js")
    @Scripts.Render("~/bundles/app")
    @Styles.Render("~/bundles/css")

    <script>
        window.baseUri = '@Url.Content("~")';
        window.token = '@ViewBag.Token';
    </script>


    <script src="@Url.Content("~/signalr/hubs")" type="text/javascript"></script>

    @RenderSection("ScriptBlock", false)
</head>
    <body class="body">
        @if (!ViewBag.HideMenu)
        {
            <nav class="navbar navbar-default" role="navigation">
                <div class="navbar-header">
                    <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#epm-navbar" type="button" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="epm-navbar">
                    <ul class="nav navbar-nav">
                        <li><a href="@Url.Action("Index", "Home")">Home</a></li>
                        <li class="dropdown">
                            <a href="#" data-toggle="dropdown" class="dropdown-toggle">Production<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("RefreshAPI", "Production")">Refresh API</a></li>
                                <li><a href="@Url.Action("ProductionMaterial", "Production")">Material</a></li>
                                <li><a href="@Url.Action("ItemBuild", "Production")">Build Items</a></li>
                                <li><a href="@Url.Action("InboundContract", "Production")">Inbound Contracts</a></li>
                                <li><a href="@Url.Action("OutboundContract", "Production")">Outbound Contracts</a></li>
                                <li><a href="@Url.Action("MarketRestock", "Production")">Post Sell Orders</a></li>
                                <li><a href="@Url.Action("MarketReprice", "Production")">Update Sell Orders</a></li>
                                <li><a href="@Url.Action("PurchaseRelist", "Production")">Post Buy Orders</a></li>
                                <li><a href="@Url.Action("PurchaseReprice", "Production")">Update Buy Orders</a></li>
                                <li><a href="@Url.Action("ItemMaintenance", "Production")">Item Maintenance</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" data-toggle="dropdown" class="dropdown-toggle">Reporting<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("ItemSales", "Reporting")">Item Sales</a></li>
                                <li><a href="@Url.Action("DailySales", "Reporting")">Daily Sales</a></li>
                                <li><a href="@Url.Action("MonthlySales", "Reporting")">Monthly Sales</a></li>
                                <li><a href="@Url.Action("ItemCostTrend", "Reporting")">Item Trends</a></li>
                                <li><a href="@Url.Action("MaterialCostTrend", "Reporting")">Material Trends</a></li>
                                <li><a href="@Url.Action("MarketResearch", "Reporting")">Market Research</a></li>
                                @if (ViewBag.IsAdmin)
                                {
                                    <li><a href="@Url.Action("TransactionAudit", "Reporting")">Transaction Audit</a></li>
                                    <li><a href="@Url.Action("SubscriberSales", "Reporting")">Subscriber Sales</a></li>
                                }
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a href="#" data-toggle="dropdown" class="dropdown-toggle">Maintenance<b class="caret"></b> </a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Configuration", "Maintenance")">Configuration</a></li>
                                <li><a href="@Url.Action("Accounts", "Maintenance")">Accounts</a></li>
                            </ul>
                        </li>
                        <li><a href="@Url.Action("Logout", "Account")">Logout</a></li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </nav>
        }

        <div class="container main">
            @RenderBody()
        </div>
    </body>
</html>

EPM.Web/Views/Shared/_Table.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title></title>
</head>
<body>
    <div>
    
    </div>
</body>
</html>